export const logout = 'logout'
export const offlineRole = 'offlineRole'
export const acessRole = 'acessRole'
export const initUserInfo = 'initUserInfo'
export const fetchLoading = 'fetchLoading'
export const changeOptions = 'changeOptions'